### ISSUE TITLE
Skills Section- Icon not Resizable 

### ISSUE THREAD

**Issue by shaurya35** [shaurya35/Portfolio-1#1]
### **Issue Description**
Skills Section

https://github.com/shaurya35/Portfolio-1/assets/106850641/78c497a7-bbde-41fc-9d72-585495facac7

_Problem_
- When attempting to adjust the CSS for icons to increase responsiveness on mobile devices, you may encounter an issue where the desired changes are not reflected. This is likely due to the existence of parent properties or global attributes that are overriding your CSS changes. To successfully modify the icon CSS for mobile devices, it is necessary to identify and address these conflicting properties.

_Solution_
- Applying a media query, we can make the skills icons smaller for mobile devices and align it accordingly. 

_Possible Fixes_
- Can be a problem of CSS property overriding the parent class or itself.

**Comment by Der12kl** [comment]
@shaurya35, I've addressed the issue with the non-resizable icons in the skills section as part of the recent updates in the pull request [#2](https://github.com/shaurya35/Portfolio-1/pull/2). I implemented media queries to ensure that the icons are now responsive and scale appropriately on mobile devices.

Please review the changes included in the pull request and let me know if there are any further adjustments you would like. I'm ready to make any additional updates to meet the project's standards. Thank you!

**Comment by shaurya35** [comment]
This issue has been resolved by @Der12kl and is now closed.
